SET REFERENTIAL_INTEGRITY FALSE;
truncate table user;
truncate table category;
truncate table company;
truncate table resume;
truncate table recruit;
truncate table apply;
truncate table subscribe;
SET REFERENTIAL_INTEGRITY TRUE;